### PR TITLE
Handle image

### PR DESCRIPTION
**Pull request by nigelgbanks**
@Tristaan  thanks for all the work you've done here its gonna be great to get this in! 

Sorry for not getting around to this sooner it took me a while to get it stood up as I wasn't familiar with the software. In particular the format of the private keys threw me for a bit of a loop as I was trying to use an RSA formatted key to get it to start.

I've made a number of minor changes to bring the image in line with the expected behaviour of the other images in that `confd` is the "source of truth" for any configuration rather than the environment as we support several backends for confd (at least in theory). As well as some general refactoring where behaviour in this new image was shared with existing images. As well as some minor issues I found during testing.

If you approve and merge these changes into your branch, I can merge your pull here https://github.com/Islandora-Devops/isle-buildkit/pull/104.

It would be good to get this in soon as I have a different pull that will be affected by these changes and require some changes. https://github.com/Islandora-Devops/isle-buildkit/pull/96

I used the following docker-compose files to test against `bdbje` `"mysql` and `postgresql` locally.

**bdbje**:
```yml
version: '3.7'
services:
  handle:
    image: local/handle:latest
    ports:
      - 8000:8000
```

**mysql**:
```yml
version: '3.7'
volumes:
  mariadb-data:
services:
  handle:
    image: local/handle:latest
    ports:
      - 8000:8000
    environment:
      HANDLE_STORAGE_TYPE: sql
      HANDLE_PERSISTENCE_TYPE: mysql
  mariadb:
    image: local/mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql:rw
```

**postgresql**:
```yml
version: '3.7'
volumes:
  postgresql-data:
services:
  handle:
    image: local/handle:latest
    ports:
      - 8000:8000
    environment:
      HANDLE_STORAGE_TYPE: sql
      HANDLE_PERSISTENCE_TYPE: postgresql
  postgresql:
    image: local/postgresql:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
```

### CODE REVIEW

**Comment by Tristaan** [comment]
Nice work! I like the way the keys are handled!
I have one question, where is the /handle prefix dropped in confd? you removed them, but the env vars still have HANDLE_ prefix.

And there are some unrelated readme changes in the first commit. I will merge them also.

**Comment by nigelgbanks** [comment]
For the `/handle` prefix there is a setting in `handle/rootfs/etc/confd/confd.toml` where in  `prefix = "/handle"` which limits and prefixes all the paths in `confd` templates with that prefix. 

We do this to isolate the configuration of each image, as some keys like `/java/opts` are used in other containers and can be specific to the image like `/fcrepo/java/opts` or `/activemq/java/opts` this way they can share a template file but have a specific value at runtime that is unique to that image.

The environment variables however will always be the full path.

**Comment by nigelgbanks** [comment]
> And there are some unrelated readme changes in the first commit. I will merge them also.

In reviewing your code I wanted to reference how other images documented the use of public / private key pairs, and I noticed that the other images didn't document their public / private key pairs so I updated them as well.

**Comment by Tristaan** [comment]
Perfect!

**Pull request merged**
